name: hkxread
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: ds841 <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  vector_math: ^2.0.5
  meta: ^1.1.2
  typed_data: ^1.1.5

dev_dependencies:
  test: ^1.3.0
