name: msktool
description: A simple console application.
version: 0.0.1
#homepage: https://www.example.com
#author: Dwayne Slater <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.0.0
  path: ^1.4.1
  file: ^5.0.6
  msk_attr:
    path: pkg/msk_attr
  msk_pf:
    path: pkg/msk_pf
  msk_util:
    path: pkg/msk_util
  msk_tex:
    path: pkg/msk_tex
  pool:
  isolate:
  vm_service_lib:

#dev_dependencies:
#  test: ^0.12.0
