name: msktool
description: A simple console application.
version: 0.0.1
#homepage: https://www.example.com
#author: Dwayne Slater <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  path: ^1.4.1
  file: ^2.3.2
  msk_attr:
    path: pkg/msk_attr
  msk_pf:
    path: pkg/msk_pf
  msk_util:
    path: pkg/msk_util
  msk_tex:
    path: pkg/msk_tex
  pool:
  isolate:
  vm_service_client:
      git:
        url: git://github.com/BlackHC/vm_service_client.git
        ref: reload_sources_poc

#dev_dependencies:
#  test: ^0.12.0
