name: msk_tex
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Dwayne Slater <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async: ^1.13.3
  msk_util:
    path: ../msk_util
  file: ^2.3.2
  image:
    path: ../image_io

dev_dependencies:
  test: ^0.12.0
