name: msk_tex
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Dwayne Slater <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: ^2.0.0
  msk_util:
    path: ../msk_util
  file: ^5.0.6
  image:
    path: ../image_io

dev_dependencies:
  test: ^1.3.0
