/// Data structures to describe attribute classes, collections, and their fields.
library msk.attr.attr_data;

import 'dart:typed_data';

/// Flags applied to classes, fields, and collections.
enum AttrFlag {
  importable,
  forced,
  readOnly,
  inheritable,
  ignoreRefCount,
  array,
  fixedArray,
  serializable,
  cloneable,
  autoGenerated,
}

/// Describes the type and size of an [AttrField].
class AttrType {
  final int id;
  final int size;

  const AttrType.raw(this.id, this.size);

  @override
  String toString() => "AttrType("
      "${id.toRadixString(16).padLeft(8, '0')}, "
      "$size"
      ")";

  @override
  int get hashCode => (size << 1) ^ id;

  @override
  bool operator ==(other) =>
      other is AttrType && other.id == id && other.size == size;
}

/// Describes a piece of data defined for an [AttrClass].
class AttrField {
  int id;
  AttrType type;
  Set<AttrFlag> flags;

  AttrField({this.id, this.type, this.flags});

  int get size => type.size;
}

/// Describes the expected data layout for some [AttrCollection]s.
class AttrClass {
  int id;
  Set<AttrFlag> flags;

  AttrClass({this.id, this.flags});
}

/// An instance of an [AttrClass], which carries data and can inherit from other
/// [AttrCollection]s.
class AttrCollection {
  int classId;
  int id;
  int parent;
  Set<AttrFlag> flags;
  List<AttrCollectionField> _fields = <AttrCollectionField>[];
  Map<int, AttrCollectionField> _fieldMap = <int, AttrCollectionField>{};
  Iterable<AttrCollectionField> get fields => _fields;
  int _nextFieldIndex = 0;
  Uint32List _fieldIds;

  AttrCollection({this.classId, this.id, this.parent, this.flags});

  void preallocateFields(int count) {
    _fields..length = count;
    _fieldIds = new Uint32List(count);
  }

  void addField(AttrCollectionField field) {
    _fields[_nextFieldIndex] = field;
    _fieldIds[_nextFieldIndex++] = field.id;
    _fieldMap[field.id] = field;
  }

  AttrCollectionField lookupField(int id) {
    // _fieldMap[id];
    /*int field;
    final int length = _nextFieldIndex;
    for (int i=0; i<length; i++) {
      field = _fieldIds[i];
      if (field == id) {
        return _fields[i];
      } else if (field > id) {
        return null;
      }
    }*/
    int min = 0;
    int max = _nextFieldIndex;
    while (min < max) {
      int mid = min + ((max - min) >> 1);
      int element = _fieldIds[mid];
      if (element == id) return _fields[mid];
      if (element < id) {
        min = mid + 1;
      } else {
        max = mid;
      }
    }
    return null;
  }
}

/// A field in an [AttrCollection].
class AttrCollectionField {
  int id;
  int inlineData;
  int staticDataLength;
  ByteData data;
  dynamic decodedData;

  AttrCollectionField(
      {this.id, this.inlineData, this.staticDataLength, this.data});
}
