name: image
version: 1.1.27
environment:
  sdk: '>=2.0.0 <3.0.0'
author: Brendan Duncan <brendanduncan@gmail.com>
description: Provides server and web apps the ability to load, manipulate, and save images with various image file formats including PNG, JPEG, GIF, WebP, TIFF, TGA, PSD, PVR, and OpenEXR.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/wiki
dependencies:
  archive: '^2.0.4'
  xml: '^3.2.1'
