name: msk_pf
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: dwayne <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.4.1
  file: ^5.0.6
  msk_util:
    path: ../msk_util

dev_dependencies:
  test: ^1.3.0
